esphome:
  name: bl0910-energy-monitor
  friendly_name: bl0910

esp8266:
  board: esp01_1m

wifi:
  ssid: "PipiHome Miao"
  password: "Pgh^voi*icVS3c!J"

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "Y9copYobNapWXbNfcGhifGPHbnvHvVwBGd4Y5Dt0UXs="
  reboot_timeout: 0s

ota:
  platform: esphome
  password: "Mjw18349276"

external_components:
  - source: bl0910-m
    
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 19200

sensor:
  - platform: bl0910-m
    update_interval: 10s # 状态更新间隔
    frequency:
      name: 'Frequency'
    temperature:
      name: 'Temperature'
    voltage:
      name: 'Voltage'
    channel_1:
      current:
        name: 'Current_1'
      power:
        name: 'Power_1'
      energy:
        name: 'Energy_1'
    channel_2:
      current:
        name: 'Current_2'
      power:
        name: 'Power_2'
      energy:
        name: 'Energy_2'
    channel_3:
      current:
        name: 'Current_3'
      power:
        name: 'Power_3'
      energy:
        name: 'Energy_3'
    channel_4:
      current:
        name: 'Current_4'
      power:
        name: 'Power_4'
      energy:
        name: 'Energy_4'
    channel_5:
      current:
        name: 'Current_5'
      power:
        name: 'Power_5'
      energy:
        name: 'Energy_5'
    channel_6:
      current:
        name: 'Current_6'
      power:
        name: 'Power_6'
      energy:
        name: 'Energy_6'
    channel_7:
      current:
        name: 'Current_7'
      power:
        name: 'Power_7'
      energy:
        name: 'Energy_7'
    channel_8:
      current:
        name: 'Current_8'
      power:
        name: 'Power_8'
      energy:
        name: 'Energy_8'
    channel_9:
      current:
        name: 'Current_9'
      power:
        name: 'Power_9'
      energy:
        name: 'Energy_9'
    channel_10:
      current:
        name: 'Current_10'
      power:
        name: 'Power_10'
      energy:
        name: 'Energy_10'
    total_energy:
      name: 'Total_Energy'
    total_power:
      name: 'Total_Power'